### ISSUE TITLE
This config file is very important. This shouldn't be on .gitignore.

### ISSUE THREAD

**Issue by dipto0321** [mcrd25/facebook-clone#41]
https://github.com/mcrd25/facebook-clone/blob/bf68dc58d4d3e0a45ff6b35b268a050d19283d6e/fbclone/.gitignore#L31

Please add this file into your project. Without this, it's really hard for me to check this project. Also, without this, you can't deploy it on Heroku. Now, You may have your development database password and username. You can avoid this. With your internal postgresql configuration, you can create a database without credentials.

**Comment by adriaanbd** [comment]
I have my own passwordless username. The standard configuration does not work on my machine due to a peer authentication failure. Ignoring this file was the quickest fix, but you're right, its crucial to have it. Could you please share that reference to configuration via hba_config file?

**Comment by dipto0321** [comment]
@adriaanbd You can try this one
[postgresql_configuration_on_ubuntu_for_rails](https://gist.github.com/p1nox/4953113)
Before trying this kind of configuration doesn't forget to backup your that configuration file. But you both can create the same username and password and can work with that. In our case, I and Ryan create the same username and password in our PostgreSQL server and we put it on the database.yml.

**Comment by dipto0321** [comment]
Done!
